name: "Create branch"
description: "Create branch in selected repo"

inputs:
  repo:
    requred: true
    type: string
  github_tkn:
    requred: true
    type: string
  files:
    requred: true
    type: string
  owner:
    requred: true
    type: string
  target_branch:
    requred: true
    type: string
  content:
    equired: true
    type: string

runs:
  using: "node12"
  main: "dist/index.js"