name: "Create branch"
description: "Create branch in selected repo"

inputs:
  repo:
    requred: true
    type: string
  github_tkn:
    requred: true
    type: string
  file1:
    requred: true
    type: string
  file2:
    requred: true
    type: string
  owner:
    requred: true
    type: string
  target_branch:
    requred: true
    type: string
  test_input:
    required: false
    type: string
    default: ''
  content:
    equired: true
    type: string

runs:
  using: "node12"
  main: "dist/index.js"