name: 'Get refs and update repo'

on:
  workflow_dispatch:

jobs:

  TestOctokit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v2
      name: Node installation
      with:
        node-version: 12

    - name: Get Branch with octo
      uses: zsvs/OctokitAction@main
      with:
        repo: OctokitAction
        owner: zsvs
        target_branch: test_anastasia_1
        main_branch: main
        github_tkn: ${{ secrets.GITHUB_TOKEN }}