name: 'Get refs and update repo'

on:
  workflow_dispatch:
    inputs:
      repo:
        requred: true
        type: string
        default: OctokitAction
      file:
        requred: true
        type: string
      owner:
        requred: true
        type: string
        default: zsvs
      target_branch:
        requred: true
        type: string
        default: test

jobs:

  TestOctokit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v2
      name: Node installation
      with:
        node-version: 12

    - name: Get Branch with octo
      uses: zsvs/OctokitAction@main
      with:
        repo: ${{ inputs.repo }}
        owner: ${{ inputs.owner }}
        file: ${{ inputs.file }}
        target_branch: ${{ inputs.target_branch }}
        main_branch: ${{ inputs.main_branch }}
        github_tkn: ${{ secrets.GITHUB_TOKEN }}